version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "8081:3000"
    volumes:
      - ".:/app"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
